name: GitHub CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.5

      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev

      - name: Setup app with migrations
        run: ./bin/setup
        env:
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres

      - name: Run rspec tests
        run: ./bin/rspec spec
        env:
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres
